### ISSUE TITLE
Why pass a Vector{UInt8} then convert to an IOBuffer?

### ISSUE THREAD

**Issue by dmbates** [JuliaData/FlatBuffers.jl#12]
I think it is easier (fewer allocations, etc.) to extract the `data` member of an `IOBuffer` as a  `Vector{UInt8}` than to create an `IOBuffer` from a `Vector{UInt8}`.  Methods like 

```julia
Base.get{T}(t::Vector{UInt8}, pos::Int, ::Type{T}) = read(IOBuffer(sub(t, (pos+1):length(t))), T)
```

can become

```julia
Base.get{T}{io::IOBuffer, pos, ::Type{T}) = read(seek(io, pos), T)
```

@quinnj Is there a reason you not want the `Table` type `bytes` field to be an `IOBuffer`?

**Comment by quinnj** [comment]
This is somewhat more an artifact of following the Go implementation. We could probably switch it, I'll have to look into it.
