### ISSUE TITLE
Revert to earlier formulation?

### ISSUE THREAD

**Issue by dmbates** [JuliaData/FlatBuffers.jl#13]
@quinnj I am beginning to think that I was too quick in suggesting that you create a pull request and in accepting that pull request without vetting it in detail.  I can't understand the current formulation and I can't even figure out how to use it.

I suggest that we go with the earlier suggestion of you creating your own repository for this FlatBuffers code and I will work with a formulation that I can understand.

**Comment by quinnj** [comment]
I think it would be more productive to have you post questions around anything that isn't working for you and I can help clarify usage and docs. This is a full, spec-based implementation, so I think we just need to polish instead of abandon.
