### ISSUE TITLE
Handle "bit_flags" in enum declaration

### ISSUE THREAD

**Issue by quinnj** [JuliaData/FlatBuffers.jl#14]
Schema code like

```
enum Color:byte (bit_flags) { Red = 0, Green, Blue = 3, }
```

becomes the following in Go

``` go
const (
    ColorRed = 1
    ColorGreen = 2
    ColorBlue = 8
)
```

the docs say:

> bit_flags (on an enum): the values of this field indicate bits, meaning that any value N specified in the schema will end up representing 1<<N, or if you don't specify values at all, you'll get the sequence 1, 2, 4, 8, ...

**Comment by rjkat** [comment]
This is handled by adding support for `flatc`.
