### ISSUE TITLE
Docs website is offline

### ISSUE THREAD

**Issue by felipenoris** [JuliaData/FlatBuffers.jl#18]
404 error

**Comment by iamed2** [comment]
Currently points to dmbates.github.io, and the repo no longer exists there. 

Luckily the docs are minimal so you can view everything at this one page: https://github.com/JuliaData/FlatBuffers.jl/blob/master/docs/src/index.md

**Comment by quinnj** [comment]
Will be fixed by e92cc45b94ae5dcd12b2a1a48423d1133762b243
